# Generated by Django 5.0.6 on 2024-09-04 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_eligibility_eligibility_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='college',
        ),
    ]
