# Generated by Django 5.0.6 on 2024-09-04 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='university',
        ),
        migrations.AddField(
            model_name='university',
            name='university',
            field=models.ManyToManyField(through='base.Eligibility', to='base.program'),
        ),
    ]
